[Interface]
PrivateKey = yL5KmSBX4TM58e8kbkZtayQfNg5WzUa3GodurraZzGA=
Address = 10.0.0.2/24
ListenPort = 51820

[Peer]
PublicKey = ppyp+sMbCCSme+ReKbWeic/m2U+gfWEgbxk/cdU8Ins=
AllowedIPs = 10.0.0.1/32
PersistentKeepalive = 25
